### ISSUE TITLE
@typescript-eslint/method-signature-style and the mixin pattern

### ISSUE THREAD

**Issue by JerryCauser** [standard/eslint-config-standard-with-typescript#1062]
**What version of this package are you using?**

`"ts-standard": "12.0.2"`
`"eslint-config-standard-with-typescript": "23.0.0"`

**What operating system, Node.js, and npm version?**
macOS 13.2.1 (22D68), nodeJS v18.14.1, npm v9.5.0

**What happened?**

I am writing some kind of mixins and faced mutually exclusive requirements of TS and ESlint:

```typescript
interface ProtoInstance {
  load: (s: string) => Promise<void>
}

type ProtoConstructor = new () => ProtoInstance

interface AInstance extends ProtoInstance {
  load: (s: string) => Promise<void>
}

type AConstructor = new () => AInstance

export class Proto implements ProtoInstance {
  async load (s: string): Promise<void> {
    console.log('proto load', s)
  }
}

export function getConstructor (Base: ProtoConstructor): AConstructor {
  return class A extends Base {
    // will say "TS2425: Class 'ProtoInstance' defines instance member property 'load',
    // but extended class 'A' defines it as instance member function."
    async load (s: string): Promise<void> {
      console.log('a load', s)

      return await super.load(s)
    }
  }
}
```

---
If I change interfaces to fulfil this requirement of TS, then ts-standard will shout me `ESLint: Shorthand method signature is forbidden. Use a function property instead.(@typescript-eslint/method-signature-style)`

```typescript
interface ProtoInstance {
  load (s: string): Promise<void> // here it will shout ESLint: Shorthand method signature is forbidden. Use a function property instead.(@typescript-eslint/method-signature-style)
}

type ProtoConstructor = new () => ProtoInstance

interface AInstance extends ProtoInstance {
  load: (s: string) => Promise<void> // for some reason everything ok with this "property" declaration
}

type AConstructor = new () => AInstance

export class Proto implements ProtoInstance {
  async load (s: string): Promise<void> {
    console.log('proto load', s)
  }
}

export function getConstructor (Base: ProtoConstructor): AConstructor {
  return class A extends Base {
    async load (s: string): Promise<void> { // now it is the silent one
      console.log('a load', s)

      return await super.load(s)
    }
  }
}
```

**What did you expect to happen?**

I've been expecting not facing mutually exclusive requirements of TS and ESlint. In my opinion the eslint requirement about "only property fields" isn't working fine right now, this is why it should be disabled for now.

**Are you willing to submit a pull request to fix this bug?**
Yes

**Comment by mightyiam** [comment]
Thank you, @JerryCauser . I'll look into this.

**Comment by rostislav-simonik** [comment]
@JerryCauser do you think that this would help you to address the issue ? 

```ts
interface ProtoInstance {
  load: (s: string) => Promise<void>
}

type ProtoConstructor = new () => ProtoInstance

interface AInstance extends ProtoInstance {
  load: (s: string) => Promise<void>
}

type AConstructor = new () => AInstance

class Proto implements ProtoInstance {
  async load (s: string): Promise<void> {
    console.log('proto load', s)
  }
}

function getConstructor (Base: ProtoConstructor): AConstructor {
  return class A extends Base {
    // here it's the property initialization, not a method declaration
    load = async (s: string): Promise<void> => {
      console.log('a load', s)
      return await super.load(s)
    }
  }
}
```

**Comment by JerryCauser** [comment]
@rostislav-simonik doesn't fit at all. By writing the method as a field of the class, we add an overhead to creating instances of the class (each object will have the same method instead of one function in prototype). Also, we cannot use correct inheritance: we cannot refer to the parent class to use the parent method, which was declared as a field (`super.load`).

**Comment by rostislav-simonik** [comment]
@JerryCauser thx for the explanation. we will revisit this in our next mob session.

**Comment by rostislav-simonik** [comment]
@JerryCauser how about this? If you don't want to use a Proto class maybe you could also introduce an intermediate abstract class such as AbstractProto which would serve as a replacement for the AConstructor type 

```ts
interface ProtoInstance {
  load: (s: string) => Promise<void>
}

// type ProtoConstructor = new () => ProtoInstance

// interface AInstance extends ProtoInstance {
//   load: (s: string) => Promise<void>
// }

// type AConstructor = new () => AInstance

export class Proto implements ProtoInstance {
  async load (s: string): Promise<void> {
    console.log('proto load', s)
  }
}

export function getConstructor (Base: typeof Proto): typeof Proto {
  return class A extends Base {
    async load (s: string): Promise<void> {
      console.log('a load', s)

      return await super.load(s)
    }
  }
}
```

**Comment by JerryCauser** [comment]
@rostislav-simonik now we cannot use correct types that will represent the AConstructor and AInstance, because it is within the mixin function.

class A as a mixin can contain additional methods and fields and it can be extended by another mixin class. Without exposing correct Interfaces of `class A` there will be no possibility to correctly use it.

Also ProtoInstance and ProtoConstructor in the current example represent any class that we want to use as a Base class. This is why `getConstructor` cannot return just `typeof Proto`. It will be correct only if our mixin don't add anything (it also could change methods even if it is not SOLID).

For example class A could also have method `async loadV2 () { ..... }`.

**Comment by rostislav-simonik** [comment]
How about this variation?

```ts
interface ProtoInstance {
  load: (s: string) => Promise<void>
}

// type ProtoConstructor = new () => ProtoInstance

// interface AInstance extends ProtoInstance {
//   load: (s: string) => Promise<void>
// }

// type AConstructor = new () => AInstance

abstract class AInstance implements ProtoInstance {
  async load (s: string): Promise<void>  { 
    throw new Error('should be implemented in inherited class')
  }
}

export class Proto implements ProtoInstance {
  async load (s: string): Promise<void> {
    console.log('proto load', s)
  }
}

export function getConstructor (Base: typeof AInstance): typeof AInstance {
  return class A extends Base {
    async load (s: string): Promise<void> {
      console.log('a load', s)

      return await super.load(s)
    }
  }
}
```

**Comment by JerryCauser** [comment]
@rostislav-simonik it's not relevant to described case

As I said I want to extend some proto classes via mixins. It will be a big waste of time in rewriting whole NodeStream class (proto class I want to extend).

Also @6XGate correctly mentioned that semantically arrow style and function style isn't the same entities in the JS. Arrow styles used to declare current field in class instance and function style used to declare a prototype class field.

**Comment by jay-bulk** [comment]
This project aims to "standardize" our codebases. If there's a choice to make between two similar ways to do the same thing, we'll choose one. And because the property style provides a little more type safety, we choose it.

We understand that the additional layer of abstract classes will introduce unbound methods. Therefore, in the context of your project it may be best to disable this rule within the referenced scope.

We're going to close this issue because we feel it's complete. If you disagree, feel free to raise your concern.

**Comment by JerryCauser** [comment]
@jay-bulk 2 concerns:
First: This rule provokes mutually exclusive requirements

Second:
> If there's a choice to make between two similar ways to do the same thing, ...

It is choice not to do the same thing. It is semantically and actually different things. One way pushes you to use instants fields (`load: (s: string) => Promise<void>`) and another explains that you are using proto class methods (`load (s: string): Promise<void>`)

Mixing them is a mistake.

**Comment by 6XGate** [comment]
I have to push back on this due to the critical semantic and actual differences. Both provide the best type-safety, if the correct style is used. This rules should be removed in its entirety from Standard as defining the wrong style is dangerous and an error. ESLint and Standards should be used to reduce errors, not promote anti-patterns and bad practices.

If you need callback or option provided functions, then property style is correct. If you need to define interfaces for classes to implement... that better be method style. It should be what the library expects.

**Comment by rostislav-simonik** [comment]
Can you please provide more specific examples and risks you see? Because it's easier to assess your cases then. 

If we pick the bound method approach for classes, it will break the overloading of methods. 
```typescript
interface IA  {
    log:  () => void
}


class A1 implements IA {
    some: number
    
    constructor (some: number) {
        this.some = some
    }

    foo1 = () => {
        console.log('some', this.some)
    }
    foo = () => {
        this.log()
    }
    log = () => {
        console.log('some 1', this.some)
    }
}

class A2 extends A1 {
    log = () => {
        super.log()
        console.log('some 2', this.some)
    }
} 


const a1 = new A2(2)

a1.foo() // [ERR]: (intermediate value).log is not a function 
a1.log() // [ERR]: (intermediate value).log is not a function 


const { foo1 } = a1
foo1() // [LOG]: "some",  2 
```

On the other hand, if we pick the unbound method approach

```typescript
interface IB  {
    log(): void
}

class B1 implements IB {
    some: number
    constructor (some: number) {
        this.some = some
    }

    foo1 () {
        console.log('some', this.some)
    }
    foo () {
        this.log()
    }
    log() {
        console.log('some 1', this.some)
    }
}

class B2 extends B1 {
    log () {
        super.log()
        console.log('some 2', this.some)
    }
} 

class B3 extends  B2 {
    log () {
        super.log()
        console.log('some 3', this.some)
    }
}

const b1 = new B2(2)
b1.foo()
b1.log()

const { foo1 } = b1
foo1() // [ERR]: Cannot read properties of undefined (reading 'some') 
```

To mitigate the risk of decomposing unbound methods by adding `this: <Class|Interface>` annotation into such methods.  Which also adds clear visibility of invocation requirements for such a method 

```typescript
    class B1 implements IB {
      ...
      foo1 (this: B1) {
        console.log('some', this.some)
      }
    }
    const b1 = new B1()
    const { foo1 } = b1
    console.log('b1.foo1()')
    foo1() // The 'this' context of type 'void' is not assignable to method's 'this' of type 'B1'.
```
There was also a proposal to create such a rule, https://github.com/typescript-eslint/typescript-eslint/issues/4964, but it got pushed back because such a rule could cause performance difficulties. Nevertheless, this does not suggest that the given rule would not be beneficial. The workaround lacking such a rule was the similar setup you were proposing. 

We also need to think about the majority of users and questions are?

* How often are most users using class, inheritance and overloading?
* How often are most users using deconstructing unbound methods of class instances?

My personal view on this is that the project above doesn't fit into the spectrum of most users, and it's completely okay to disable/change a few rules. Such projects usually have more complex patterns for the benefit of others (consumers), but not necessarily follow the pattern of most users. 


If you are willing to showcase how to mitigate those risks differently, feel free to use this [typescript playground] (https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgJIEFnIN4FgBQWWANgPYDmAXFgBQCUyAvAHzIBupwAJgQL4ED8CYnADOo5OgCMyYAFsADsQhyI4CRhwEiyUaVXUQAVzkAjaNqKWsCUiFFgoRhGFJRkNPQeTGz0BniEOkRgABbAogB0XiiMuvoQ1sj8+EkwpKQycfRMrIHBRLb2pMqRZOQ0AOQxlQA0yGER0Ql0SSk66aRMHgwsWkEFjVHl9G1J5d05ffkFyEV6pSPVCchSdQ3hUTGtA8l8gsJiEugATMgQAB6QIFzHMjMkFJO9eUk6okYK0GUUo7s68xKEB+FWWqmQJ3WQ2aqh2OhSvGQglAkFgiBQqAAQlgHsgRnRqBxuPtUkIROJkJiZPIlCo1GANNjcTFDCZzFAkvNHM5XO5PAlWX4oAE3iFNjDYvFVGNSR0MjIcriAXYFsCljV6tDtjK5V1FaKsND8TqiPj+rM5iqgSCqjFVlDxdrdgiDuSJJizpdrrdKfdxk99f8iB8vlAbXDZoDFr8wShIZrHS0ZYjXUdKQBmc5XNQ+ylnXETQMWkPfY1BmxW6Ogu3ph1NJ3wkkHFVgZBwLI+CAAd0kJxoJx2BEcAE8cFZdlG1TH25FOvRKhGsDO5ztEQg4GAEKEPNAoG4RRPK8Dd24aCfhU38COx1hOUebZUZ-iF0kn79V3MN1ud1A98LzYU97nmev77peXJjp0MiInE7YEJOD7LvK847FBfzNvYramB2IDdnm-Y7AhSzYbOGQoQQJErvB97EVI4YvvgJFlkOUCjriEHYMgUHJN02F3sUVZVJRyF0AxupSH8a5ftuIF-geyoCceoFQLJYH4LwQA)

**Comment by 6XGate** [comment]
Your first example is not overridden methods. It's actual property assignment of closures as bound functions, with `this` _bound to_ the class since they are in the context of the constructor. This is very much not how method overloads should be implemented in class syntax. The correct syntax would be the classic signature style. But `foo1` is expected to be bound, or not reference the object it's a property of. In which case the error signature would be fine.

Here is an example for why the correct style must be specified. This assume `@typescript-eslint/unbound-method` is also enabled.

```typescript
interface ILogger {
  log(): void
}

class Logger implements ILogger {
  log() {
    console.log('test')
  }
}

interface LogginOptions {
  log: () => void
}

function runBound(options: LogginOptions) {
  const { log } = options
  log()
}

function runUnbound(logger: ILogger) {
  const { log } = logger
  //      ^^^ ESLint catches that I destructored an unbound method via ILogger. (@typescript-eslint/unbound-method)
  // Had the method-style been forced to an array style, this would not be noticed.
  log()
}

const logger = new Logger()

runBound({
  log: () => {
    console.log('test')
  }
})

runUnbound(logger)
```

Now there are some deficiencies with `@typescript-eslint/unbound-method` such as not catching destruction in the argument list of a function. And nothing enforces the style of an interface implementer. But it does allow some safety in places it does work.

**Comment by rostislav-simonik** [comment]
@6XGate I'm quite aware of that, and exactly with property method syntax you are not able to achieve that. The question is more general if somebody ends up with class implementations, what would be their intention in the most user case? 

I wanted to demonstrate in both method styles a similar pattern and the negative outcomes. Each has its own one. 

In the method signature style, we can mitigate the problem by introducing the annotation, but in the property signature style, you won't be able to mitigate the demonstrated problem. 

That's why I ended up with the conclusion, but not necessarily, that method style signature is the more viable option.

**Comment by mightyiam** [comment]
@6XGate @JerryCauser would any of you be interested in joining us for a live session trying to understand each other well?

**Comment by mightyiam** [comment]
A little bit of a reset of this discussion. Or a recap, if I may.

The reason—the only reason—for enabling this rule (@typescript-eslint/method-siganture-style) is the one described in [its documentation](https://typescript-eslint.io/rules/method-signature-style). Property style interface functions are type checked contravariantly under `strictFunctionTypes`. And that is additional type safety. Again: that is the only benefit of this rule, it seems.

One point to note, for the purpose of not being confused, is that this rule applies only to _interface_ member functions. It doesn't apply to class function members. So, the following would be okay:

```ts
class A {
  m(): void {}
}
```

It may be that your (@JerryCauser) use case justifies relaxing this rule, but we have read this thread over and realized that we don't understand your use case. You seem to be describing a pattern—a "mixin" pattern—that we may not be familiar with. Would you mind providing reference or explaining this pattern, providing more thorough and concrete examples?

Likewise, @6XGate, could you please provide examples for what you are concerned about and have explained [here](https://github.com/standard/eslint-config-standard-with-typescript/issues/1062#issuecomment-1561576376)?

**Comment by 6XGate** [comment]
I might be able to join.

If it help to understand this more. The main concern is that different projects depend on frameworks that use differing styles of objects. With the original settings that were on the rule (property style), it worked well with Vue and React, but other frameworks or extendable tools such as Laravel Mix would likely use classic OOP and require method style for ensuring that methods aren't destructored or taken unbound.

I'm of the belief this rules doesn't work well with the unbound method rule since it would be up to the interface or type to define the proper style that might be required or preferred.

**Comment by mightyiam** [comment]
I'm glad to hear you'd be willing to join a session, @6XGate.
They occur weekly on Saturdays, 5am UTC for 2.5 hours.
Would that be convenient?

**Comment by mightyiam** [comment]
@6XGate message me if you're interested. My details are in my profile.

**Comment by mightyiam** [comment]
That's alright. Message me when you feel up for it.

**Comment by mightyiam** [comment]
Regarding the mixin pattern part of this conversation.

We have permitted ourselves to rewrite your original example, @JerryCauser, to be more complete. And following that is an equivalent example that is using a similar pattern, but using abstract classes, compatible with this rule as it is currently configured and with strict TypeScript.

```ts
interface StoreInterface {
  write: (data: string) => void
}

class DbStore implements StoreInterface {
  write (_data: string): void {
    // write to db
  }
}

class FsStore implements StoreInterface {
  write (_data: string): void {
    // write to fs
  }
}

function extendStoreClass (BaseStore: new () => StoreInterface, debug: boolean): (new () => StoreInterface) {
  if (debug) {
    return class StoreLoggerMixin extends BaseStore {
      // error TS2425: Class 'StoreInterface' defines instance member property 'write', but extended class 'StoreLoggerMixin' defines it as instance member function.
      write (data: string): void {
        console.log('storing: ', data)
        super.write(data)
      }
    }
  }

  return BaseStore
}

let StoreClass: new () => DbStore
let store: StoreInterface

StoreClass = extendStoreClass(DbStore, false)
store = new StoreClass()
store.write('some data')

StoreClass = extendStoreClass(DbStore, true)
store = new StoreClass()
store.write('some data')

StoreClass = extendStoreClass(FsStore, false)
store = new StoreClass()
store.write('some data')

StoreClass = extendStoreClass(FsStore, true)
store = new StoreClass()
store.write('some data')
```

The abstract class pattern:

```ts
interface StoreInterface {
  write: (data: string) => void
}

abstract class AbstractStore implements StoreInterface {
  write (_data: string): void {
    throw new Error('not implemented')
  }
}

class DbStore extends AbstractStore {
  write (_data: string): void {
    // write to db
  }
}

class FsStore extends AbstractStore {
  write (_data: string): void {
    // write to fs
  }
}

function extendStoreClass (BaseStore: new () => AbstractStore, debug: boolean): (new () => StoreInterface) {
  if (debug) {
    return class StoreLoggerMixin extends BaseStore {
      // no error
      write (data: string): void {
        console.log('storing: ', data)
        super.write(data)
      }
    }
  }

  return BaseStore
}

let StoreClass: new () => DbStore
let store: StoreInterface

StoreClass = extendStoreClass(DbStore, false)
store = new StoreClass()
store.write('some data')

StoreClass = extendStoreClass(DbStore, true)
store = new StoreClass()
store.write('some data')

StoreClass = extendStoreClass(FsStore, false)
store = new StoreClass()
store.write('some data')

StoreClass = extendStoreClass(FsStore, true)
store = new StoreClass()
store.write('some data')
```

So, we don't see "can't do mixin pattern" as a reason to disable this rule.

Different codebases having different patterns in place also doesn't seem like a reason for this project to avoid trying to define rules that encourage best practices.

We will next proceed to examine how this rule relates to the topic of unbound methods.

**Comment by mightyiam** [comment]
Following up, we've changed the title of this issue to refer to the mixin pattern specifically.

And we're closing it, as it seems we've demonstrated that the mixin pattern can be achieved. Sorry for any inconvenience with regards to existing implementations that do trigger this rule.

With regards to safety of unbound methods, we've opened #1327 .

For any other issues that relate to this rule, please open a new issue or discussion.

If you still disagree, please comment here.
