### ISSUE TITLE
Automated release

### ISSUE THREAD

**Issue by mightyiam** [standard/eslint-config-standard-with-typescript#107]
I'd like one of those shiny automated CI release workflows, please.

**Comment by feross** [comment]
I'm personally not a fan of this since you must give the CI instance your npm password. You're welcome to do this for `eslint-config-standard-with-typescript` but I'm going to keep publishing `standard` by hand. :)

Btw, if you find publishing is a lot of work, you might like to use these terminal aliases that I use to publish quickly:

```bash
alias patch='preversion && npm version patch && postversion'
alias minor='preversion && npm version minor && postversion'
alias major='preversion && npm version major && postversion'
alias preversion='git pull && git diff --exit-code && git diff --staged --exit-code && npm pack --dry-run --ignore-scripts && rm -rf node_modules/ && npm install && npm test'
alias postversion='git diff --exit-code && git diff --staged --exit-code && npm run --if-present update-authors && (git diff --exit-code || git commit -am "update authors") && npm run --if-present build && (git diff --exit-code || git commit -am "build") && git push && git push --tags && npm publish'
```

Now you can just run `patch`, `minor`, or `major` to publish a new version. It handles a lot of the boring details for you.

**Comment by mightyiam** [comment]
Thank you for the tips, @feross .

**Comment by feross** [comment]
Of course :)
