### ISSUE TITLE
@typescript-eslint/no-non-null-assertion vs. @typescript-eslint/non-nullable-type-assertion-style

### ISSUE THREAD

**Issue by jerome-benoit** [standard/eslint-config-standard-with-typescript#1378]
Both rules are enabled and they are incompatible: 

```ts
var: string | undefined
```

```ts
var as string
```
=> @typescript-eslint/no-non-null-assertion error

```ts
var!
```
=> @typescript-eslint/non-nullable-type-assertion-style error

**Comment by mightyiam** [comment]
Thank you, @jerome-benoit. Both implementations are "unsafe" and therefore are linted against. The correct implementation is a non null assertion (because it is more specific) and an eslint-disable-next-line comment, with possible a comment for the reader, as well, explaining why this is known to be non-null.

Would you agree? Closing, but feel free to argue against.
