### ISSUE TITLE
@typescript-eslint/require-await is not worth the occasional eslint-disable comment

### ISSUE THREAD

**Issue by LinusU** [standard/eslint-config-standard-with-typescript#217]
**What version of this package are you using?**

11.0.1

**What operating system, Node.js, and npm version?**

macOS Mojave, Node.js 12.12.0, npm 6.11.3

**What happened?**

I started out with this:

```typescript
import { Request } from 'express'

export async function foobar (req: Request): Promise<void> {
  throw new Error('Not implemented')
}
```

It gave me:

> Async function 'foobar' has no 'await' expression. (@typescript-eslint/require-await)

So I removed `async`:

```typescript
import { Request } from 'express'

export function foobar (req: Request): Promise<void> {
  throw new Error('Not implemented')
}
```

Then I got:

> Functions that return promises must be async. (@typescript-eslint/promise-function-async)

**What did you expect to happen?**

Have one of them work 😅 

**Are you willing to submit a pull request to fix this bug?**

Sure thing!

**Comment by LinusU** [comment]
Actually, I just realised that changing to function to non-async makes it throw instead of returning a rejected promise.

I think that the best solution would be to silence `@typescript-eslint/require-await` if there is a `throw` in the body of the function 🤔 

Open to suggestions!

**Comment by mightyiam** [comment]
Thank you for the input, @LinusU. How about returning a rejected promise?

```ts
import { Request } from 'express'

export async function foobar (req: Request): Promise<void> {
  return Promise.reject(new Error('Not implemented'))
}
```

Haven't tried.

**Comment by felskov** [comment]
@mightyiam I'm also having issue with these rules conflicting. I'm returning a promise created by a third party library like so:

```ts
function buildQuery ({ pool: Pool }) {
  return async function query<T> (queryConfig: QueryConfig): Promise<Result<T>> {
    return pool.query(queryConfig)
  }
}
```

I could add `return await`, but that throws a no-return-await error 😅

**Comment by mightyiam** [comment]
@felskov, I suspect that in your example, `pool.query` might be missing type information, preventing `@typescript-eslint/require-await` from allowing it.

Also, @LinusU, I have checked the solution that I have proposed for you issue and it seems to be working for me.

So I'm closing this issue. If anyone else feels this is still an issue, please comment.

**Comment by LinusU** [comment]
Hmm, I personally feel that it seems very weird to return `Promise.reject(_)` or `Promise.resolve(_)` from an `async function` 🤔 

I ran into a few more cases today which makes me vote for disabling `requiring-await` since I don't really see what value it provides.

1) Just returning an empty object (I'm complying to an interface with async functions, and this implementation should just return an empty object):

```ts
async function finalizePayment (_: ProviderSpecificInfo): Promise<ProviderSpecificInfo> {
  return {}
}
```

Here it forces me to type `Promise.resolve({})` instead of `{}` which not only creates a double wrapped promise which has to be flattened, it also looks weird (I guess subjective maybe, but come on 😁)

2) Turning `throw` from called functions into Promise rejection:

```ts
async function validateOrderInput (input: OrderInput): Promise<void> {
  validateName(input.name)
  validatePhone(input.phone)
  // ...
}
```

In this case the only alternative to `eslint-ignore`ing the rule seems to be to wrap the entire function in `try`/`catch` and then doing `return Promise.reject(err)` in the catch 😬 

-----

I'm also not sure which scenarios this rule is supposed to prevent. The description says:

> Asynchronous functions that don't use await might not need to be asynchronous functions and could be the unintentional result of refactoring.

But that doesn't really happen here since you have to specify a return type of the function, and we force every `Promise<_>` returning function to be an async function.

With this in mind I feel quite strongly that we remove the `require-await` rule. Any thoughts? ☺️

**Comment by mightyiam** [comment]
@LinusU thank you for you input. I have just prioritized another parser/plugin upgrade over this, but I will get to this. I promise. And do the right thing. Please review that, if you can. #223.

**Comment by mightyiam** [comment]
> I'm complying to an interface with async functions, and this implementation should just return an empty object

Assumptions:
1. A library we are using ("not our code") has a TypeScript type that expects the user to provide an async function.
1. To comply with this requirement, we provide an async function. We would not like to work around this requirement. Let's call it `mayBeSyncForAllWeCare`.
1. The return value of `mayBeSyncForAllWeCare` must be `Promise<{}>`.

So we try:

```ts
receiveAsyncFunc(
  async function mayBeSyncForAllWeCare (): Promise<{}> {
    return {}
  }
)
```

But `@typescript-eslint/require-await` does not allow that, because it requires an async function to at least one of:
   1. use `await`
   1. return a value that is already a promise

So, with the rule in place, the only reasonable solution seems to be the latter:

```ts
receiveAsyncFunc(
  async function mayBeSyncForAllWeCare (): Promise<{}> {
    return Promise.resolve({})
  }
)
```

If we remove the rule, we are allowing async functions that could as well be sync. Such as ours. And that, _even outside of the context of some API requesting an async function_. And that does not seem to me like a rule we would like to give up on, even at the price of the extra `Promise.resolve` call.

Does this change your mind at all, @LinusU ? Please share.

**Comment by LinusU** [comment]
> A library we are using ("not our code")

This could also be our own code. It might be that some implementations of an interface does something async, and some of them doesn't need to do anything async. The interface still needs to be an async function to cover everything, and allow the sync implementations to, in the future, switch to async whilst still conforming to the same interface.

> If we remove the rule, we are allowing async functions that could as well be sync. Such as ours. And that, even outside of the context of some API requesting an async function.

Hmm, I do agree that this is a good point. I'm kind of on the fence now 😄

**Comment by mightyiam** [comment]
Thank you for sharing, @LinusU.

I feel that `receiveAsyncFunc` should be changed to expect a union of an async function and a sync function. And that our rule is desired. And that the workaround is reasonable.

So I'll close this and if you find yourself on the other side of the fence, please share your view point.

**Comment by swansontec** [comment]
Issue #249 introduced a new, different reason why `require-await` should be disabled. However, since that issue is now locked, I will reply here as requested.

This issue considers the question of whether `require-await` is useful in isolation. However, it does not consider the fact that upstream Standard.js *also* has access to this rule, and has chosen not to adopt it. Even if `require-await` is useful on its own, matching what upstream does may be even more valuable.

Upstream Standard.js considered this same question, and came to the opposite conclusion. Their reasoning was that `async` has three effects:

1. The function always returns a promise.
2. The function never throws an exception.
3. The function can use the `await` keyword.

The `require-await` rule makes sense if you only think the last effect is useful, they reason, but there are plenty of cases where you might just want the first two independently.

I do admit that `@typescript-eslint/require-await` version allows the `Promise.resolve` loophole that the plain ESLint version doesn't have. However, it's a loophole, and not at all intuitive. The fact that both @LinusU and myself *independently* ran into this case and filed bug reports should tell you something about the ergonomics of the situation. I don't think the existence of this non-obvious workaround is enough to justify deviating from upstream's decision.

**Comment by LinusU** [comment]
_crossposting what I wrote in the other issue:_

This is the ecosystem breakage report for normal Standard:

```text
1..219
# tests 219
# pass  212
# fail  7
```

Three of the fails only had rule violations in test/example code.

-----

That being said, I would still be open to removing this rule, but was convinced to keep it last time it was discussed 😅

**Comment by swansontec** [comment]
> This is the ecosystem breakage report for normal Standard:

I'm not sure what this is measuring. Is this the number of projects that would break if upstream Standard.js were to adopt the `require-await` rule?

**Comment by LinusU** [comment]
> I'm not sure what this is measuring. Is this the number of projects that would break if upstream Standard.js were to adopt the require-await rule?

Yes it is. We usually run this before deciding on adding a rule or not, and we only add rules that have a low number here.

That being said, I'm still not convinced that we should add the `require-await` rule in Standard vs. removing it here

**Comment by swansontec** [comment]
I can add some more thoughts. As projects grow in size, contracts become more important than internal implementation details. This is especially true for libraries, where the adjusting the public API requires a major version bump.

When a public API returns a promise, there is a general ecosystem-wide assumption that it will never throw an exception. The `promise-function-async` rule is very much in-line with this convention, so that's fine.

I personally work on a library that has a massive `async` API. The library implements an entire crypto-currency wallet backend, so it has hundreds of methods on dozens of objects. All the public methods are `async`, since we are capable of running in a WebWorker to avoid blocking the GUI thread. We definitely want to use the `async` keyword on all of our public methods, regardless of implementation. A method might start like this:

```typescript
async getBalance () {
  const txs = await this.loadTransactions()
  let sum = 0
  for (const tx of txs) { ... }
  return sum
}
```

But them become like this:

```typescript
async getBalance () {
  const txs = this.cachedTransactions
  let sum = 0
  for (const tx of txs) { ... }
  return sum
}
```

The function needs to remain `async`, since this is public API we are exposing, and we do have a WebView wrapper on some platforms. The fact that the implementation happens to be sync is irrelevant. Why do I need to add a redundant `Promise.resolve` to the last line, when the first line was the one that changed? The `async` keyword already handles this.

**Comment by mightyiam** [comment]
Thank you, @swansontec.

Regarding the obvious-ness of returning `Promise.resolve(value)` I am not concerned. TypeScript users who also use a linter are expected to be able to read the rule, if you ask me.

I do like my argument:

> If we remove the rule, we are allowing async functions that could as well be sync. Such as ours. And that, _even outside of the context of some API requesting an async function_. And that does not seem to me like a rule we would like to give up on, even at the price of the extra `Promise.resolve` call.

And I feel that it's worth it.

And regarding the public API (or any API) concern: Perhaps the API could be relaxed to allow normal functions, as well? Would that be a breaking change? Would that be an undesired change for some reason? Could you please explain this:

> We definitely want to use the async keyword on all of our public methods, regardless of implementation

**Comment by swansontec** [comment]
> > If we remove the rule, we are allowing async functions that could as well be sync. Such as ours. And that, _even outside of the context of some API requesting an async function_. And that does not seem to me like a rule we would like to give up on, even at the price of the extra `Promise.resolve` call.

In my entire programming career, I have encountered exactly one function that was `async` but didn't need to be, and that case was caught by the Typescript type system, not `require-await`. On the other hand, I encounter false positives from `require-await` all the time, in dozens of places across several repos.

Maybe our app is an anomaly, since we are *extremely* async-heavy. In an earlier comment, you stated that you don't use `async` much. I find that backends tend to be more async-heavy than frontends, and my work is quite backend-heavy. On the other hand, perhaps that makes my experience even more relevant, since I'm kinda the target audience of this `async` linting?

> And regarding the public API (or any API) concern: Perhaps the API could be relaxed to allow normal functions, as well? Would that be a breaking change? Would that be an undesired change for some reason? Could you please explain this:
> 
> > We definitely want to use the async keyword on all of our public methods, regardless of implementation

Suppose I publish a library, on NPM, let's call it `price-feed`. You use the library like this:

```typescript
import { PriceFeed } from 'price-feed'

const feed = new PriceFeed()
const price = await feed.getPrice('BTC')
```

Now, suppose I add an cache to this library, so `getPrice` no longer needs to be async. I can't actually remove `async` from `getPrice` without a major version bump, though, since that would break anybody using the library. If they happen to do `feed.getPrice().then()`, for example, their code will crash. I don't know who my users even are, or even if they are using Typescript, since this is on NPM.

Maybe a major version bump makes sense for a tiny library like this fake example, but for a giant library with hundreds of methods, I wouldn't want to do a major bump unless there was a solid reason. Thus, I would leave the method `async` for stability reasons.

**Comment by mightyiam** [comment]
Thank you for explaining, @swansontec. Could you explain how the addition of cache could make the `getPrice` function synchronous, please?

**Comment by swansontec** [comment]
> Thank you for explaining, @swansontec. Could you explain how the addition of cache could make the `getPrice` function synchronous, please?

Yes, I can sketch out the general idea, but bear in mind that this is a toy example.

Before, `getPrice` directly does the network request:

```typescript
class PriceFeed {
  async getPrice (currencyCode: string): Promise<number> {
    const response = await fetch(`https://api.some-exchange.com/${currencyCode}`)
    return response.json()
  }
}
```

After the change, a WebSocket keeps the prices updated in memory, and `getPrice` just returns the latest value:

```typescript
class PriceFeed {
  private cache: { [currencyCode: string]: number } = {}

  constructor () {
    const connection = new WebSocket('https://api.some-exchange.com/feed')
    connection.onmessage = event => {
      const { currency, price } = JSON.parse(event.data)
      this.cache[currency] = price
    }
  }

  async getPrice (currencyCode: string): Promise<number> {
    return this.cache[currencyCode]
  }
}
```

Again, this is just a super-sketchy toy example with a lot of bugs, so don't take it too literally. However, it does illustrate the sort of internal change that can happen in a real system.

This really happened to our `EdgeContext.pinLoginEnabled` method. Before, we would re-load the account data on each method call. This was slow, so we fixed our code to load the user data once at start-up. Now `pinLoginEnabled` is faster because it doesn't need to wait for anything, but it still returns a promise so our customers don't need to re-write their software.

---

If that seems too contrived, how about another example? We use a mock `fetch` function in a lot of our unit tests:

```typescript
async function fakeFetch (uri: string): Promise<FakeResponse> {
  return new FakeResponse(uri)
}

class FakeResponse {
  // constructor, etc....

  async text (): Promise<string> {
    return JSON.stringify({ success: true }) // mock response
  }
}
```

Obviously, neither `fakeFetch` nor `FakeResponse.text` actually need to wait for anything, since they just return static data. On the other hand, their whole point is to emulate the `fetch` API, where those functions really are async.

---

I'm sure I could think of other examples, but I guess my point is that the assumption behind `require-await` rule is incorrect. If a user goes through the trouble of using `async` and making Typescript happy about that, they probably have a darned good reason for doing all that work (as in the examples above). We shouldn't assume that they made a mistake.

On the flip side, `require-await` isn't actually helping much. It isn't catching bugs in the sense of "incorrect behavior", since Typescript + `@typescript-eslint/no-misused-promises` + `@typescript-eslint/no-floating-promises` already manage that. An extra `async` that passes these other rules is completely harmless, so why are we so eager to get rid of it?

**Comment by mightyiam** [comment]
Thank you for the examples, @swansontec .

> After the change, a WebSocket keeps the prices updated in memory, and `getPrice` just returns the latest value:

It does not seem contrived, because I know it's real. But something does not make sense to me. If the user called `getPrice` before the cache is populated, it seems that it would return undefined. Is that taken care of somehow?

> We use a mock `fetch` function in a lot of our unit tests:

A mock would be a good example of where contrived code like `Promise.resolve('primitive')` is expected.



> On the flip side, `require-await` isn't actually helping much. It isn't catching bugs in the sense of "incorrect behavior", since Typescript + `@typescript-eslint/no-misused-promises` + `@typescript-eslint/no-floating-promises` already manage that. An "extra" `async` that passes these other rules is completely harmless, so why are we so eager to get rid of it?

That's a good point. In the context of a function that must be async because of external reasons, `require-await` seems redundant and `Promise.resolve('primitive')` is equivalent to an `// eslint-disable`. Because, like you said — TypeScript and other rules take care of those.

The question remains, should this be allowed without an ESLint comment, where nothing external is compelling it to be async?

```ts
const foo = async () => 1
```

Yes, TypeScript would make sure that call sites are aware that it is a promise being returned from that function, and that would be handled. But the point is that it does not have to be a promise. And `require-await` seems to be the only way to prevent this mistake. Am I right?

**Comment by LinusU** [comment]
I personally prefer

```js
const foo = async () => 1
```

to

```js
const foo = () => Promise.resolve(1)
```

for the same reasons why we already have the `@typescript-eslint/promise-function-async` rule enabled.

Also, in the latest version we now require `await` on promises in the return position so in order to have an async function that returns `1`, you currently need to do:

```typescript
async function foo (): Promise<number> {
  return await Promise.resolve(1)
}
```

(and now seeing that I kind of want a rule that disallows `await Promise.resolve(_)` in favour of `await _`, and disallows `await Promise.reject(_)` in favour of `throw _`)

-----

That being said, I still think that the most important thing is that we match upstream here. So either we should add it there or remove it here. Do we all agree with this? ☺️

**Comment by mightyiam** [comment]
> I personally prefer
> 
> ```js
> const foo = async () => 1
> ```
> 
> to
> 
> ```js
> const foo = () => Promise.resolve(1)
> ```
> 
> for the same reasons why we already have the `@typescript-eslint/promise-function-async` rule enabled.
> 
> Also, in the latest version we now require `await` on promises in the return position so in order to have an async function that returns `1`, you currently need to do:
> 
> ```ts
> async function foo (): Promise<number> {
>   return await Promise.resolve(1)
> }
> ```
> 
> (and now seeing that I kind of want a rule that disallows `await Promise.resolve(_)` in favour of `await _`, and disallows `await Promise.reject(_)` in favour of `throw _`)
> 

I feel it should be
```ts
const foo = async () => 1 // eslint-disable-line @typescript-eslint/require-await
```

A disable comment belongs here because this function is "unnaturally" async, because of some external necessity. So that would be the correct way of handling this kind of false-positive, instead of a workaround redundant `Promise.resolve` call. Right?

> That being said, I still think that the most important thing is that we match upstream here. So either we should add it there or remove it here. Do we all agree with this?

I would vote for adding upstream and suggesting a disable comment as a workaround for the false-positive. How would others feel about that?

**Comment by swansontec** [comment]
> But something does not make sense to me. If the user called `getPrice` before the cache is populated, it seems that it would return undefined. Is that taken care of somehow?

Yes, this is probably a bug in the fake price-feed example. Our real system doesn't have this bug, though, either because we have some way to fully load the answer ahead of time, or because  returning a stale value is fine. Synchronizing with a blockchain is a long & slow process, so users expect their balance to be out of date while the loading bar is still showing.

> The question remains, should this be allowed without an ESLint comment, where nothing external is compelling it to be async?
> 
> ```ts
> const foo = async () => 1
> ```

I believe this should be allowed without an ESLint comment. It's perfectly safe & valid code, with zero downsides that I can see. It is perfectly obvious what this function does, too - it returns a promise resolved to `1`. What, exactly, are we trying to save the programmer from?

**Comment by mightyiam** [comment]
> > The question remains, should this be allowed without an ESLint comment, where nothing external is compelling it to be async?
> > ```ts
> > const foo = async () => 1
> > ```
> 
> I believe this should be allowed without an ESLint comment.

According to your testimony, you have a lot of this code and it is a relic from a previous public API that you justly refrain from breaking. So, however common such a situation is, I don't feel that it is ideal code style. Perhaps in your project the right thing to do would be to disable `require-await` — at least for a sub-directory that contains these functions.

> It's perfectly safe & valid code, with zero downsides that I can see. It is perfectly obvious what this function does, too - it returns a promise resolved to `1`.

True, but it may not be clear why the function is asynchronous.

> What, exactly, are we trying to save the programmer from?

We are trying to save the user an unnecessarily asynchronous part of an execution path. And also from making a choice whether this function will be sync or async.

**Comment by swansontec** [comment]
This thread seems to hinge on the following assumption:

- sync = good
- async = bad

In fact, the assumption is that async is so bad, we should sacrifice the following use-cases just to get rid of a few extra `async` keywords:

- Maintaining stable API's
- Mocking async functions
- Satisfying third-party libraries

In exchange for sacrificing these use-cases, what do we get? Fewer bugs? Nope! The `async` statements that `require-await` caches are completely harmless, since Typescript + `@typescript-eslint/no-misused-promises` + `@typescript-eslint/no-floating-promises` already get rid of the buggy ones.

In fact, thanks to Typescript, it's already *really hard* to create accidental `async` functions. I can think of very few situations where you can simply toggle `async` on and off without creating type errors at all the downstream call sites. One of the few cases I can think of is `mocha`, which lets tests be either sync or async. Mocha lets you write things like this:

```typescript
describe('mocha tests', function () {
  it('can be sync', function () {
    expect(1 + 1).equals(2)
  })

  it('can be async', async function () {
    expect(1 + 1).equals(2)
  })
})
```

Both tests work exactly the same, including error handling, so there is no meaningful run-time difference here. However, the assumption is that some horrible catastrophe will happen if the second test continues to exist. Standard must eliminate it at all cost! Solid engineering practices like mocks or stable API's seem "contrived" or "unnatural" compared to the magnitude of this disaster, so them use workarounds. We must destroy that extra `async`!

I don't get it, though. Aside from a few unnecessary characters, what's actually wrong with the second unit test? I get that the `async` doesn't need to be there, but what actual harm is it causing?

**Comment by mightyiam** [comment]
Thank you for caring enough to continue this conversation, @swansontec.

> This thread seems to hinge on the following assumption:
> 
> * sync = good
> * async = bad

The assumption is that for a function to be async there should be a good reason. It seems clear that async functions add programming overhead (handling of returned promise as opposed to final value) and performance overhead (that I've never seen measurement of).
 
> In fact, the assumption is that async is so bad, we should sacrifice the following use-cases just to get rid of a few extra `async` keywords:

The sacrifice is in the form of

```ts
// eslint-disable-next-line @typescript-eslint/require-await
```

> * Maintaining stable API's

Falls into the category where linting cannot understand that your usage of async is necessary and therefore we get a false-positive that we must place a comment on.

> * Mocking async functions

Ditto. Having funny code that breaks linting in mocks seems common enough to me.

> * Satisfying third-party libraries

Are you talking about a case where a library accepts only an async function but your implementation is able to obtain the value synchronously? If that is the case, then it seems like a flaw in the library. Perhaps it would be more appropriate to accept a union type of an async and a sync function there? If that is the case, then that is another case of an "unnaturally async" function, for external reasons, that the linter does not currently understand. By the way, perhaps this is one case the rule can be modified to understand.

> In exchange for sacrificing these use-cases, what do we get? Fewer bugs? Nope! The `async` statements that `require-await` caches are completely harmless, since Typescript + `@typescript-eslint/no-misused-promises` + `@typescript-eslint/no-floating-promises` already get rid of the buggy ones.

Yes, it is not about preventing bugs. It is merely preventing unnecessary complexity. The author must justify a function being async, if the linter does not find a justification.

> In fact, thanks to Typescript, it's already _really hard_ to create accidental `async` functions. I can think of very few situations where you can simply toggle `async` on and off without creating type errors at all the downstream call sites.

That's true. TypeScript knows that the return type of an async function is always `Promise<T>`, so call sites must handle return value accordingly.

>One of the few cases I can think of is `mocha`, which lets tests be either sync or async. Mocha lets you write things like this:
> 
> ```ts
> describe('mocha tests', function () {
>   it('can be sync', function () {
>     expect(1 + 1).equals(2)
>   })
> 
>   it('can be async', async function () {
>     expect(1 + 1).equals(2)
>   })
> })
> ```
> 
> Both tests work exactly the same, including error handling, so there is no meaningful run-time difference here. However, the assumption is that some horrible catastrophe will happen if the second test continues to exist. Standard must eliminate it at all cost! Solid engineering practices like mocks or stable API's seem "contrived" or "unnatural" compared to the magnitude of this disaster, so make them use workarounds. We must destroy that extra `async`!

Just a comment to let the linter know you have a good reason for this function being async. And consider a global comment at the top of the test module:

```ts
// eslint-disable @typescript-eslint/require-await
```
 
> I don't get it, though. Aside from a few unnecessary characters, what's actually wrong with the second unit test? I get that the `async` doesn't need to be there, but what actual harm is it causing?

Not causing harm does not seem to be an argument. Semicolons at the end of lines also do not cause harm. Nor do dangling commas (which I personally prefer, by the way). But Standard makes code style decisions.

It ends up being a choice between stricter linting (which I personally like) which requires a disable-comment some times and more permissive linting that gets out of your way by not requiring that of you. I prefer the former and you seem to not see enough benefit in it. Perhaps affected by having code with frequent such occurrences. What would help is input from more users.

**Comment by swansontec** [comment]
> Thank you for caring enough to continue this conversation, @swansontec.

Thanks, I do care an awful lot about code quality, maybe a bit too much. It seems like I am always here trying to get rules adjusted.

> The sacrifice is in the form of `// eslint-disable-next-line @typescript-eslint/require-await`

Yes, and this is a big deal. Linting is a balancing act. If the linter is too loose, bugs slip through. If the linter is too strict, it trains its users to ignore its suggestions, which is even worse.

This happened to our original frontend team, who got in the bad habit of silencing Flow errors. I am still trying to clean up the mess they created, years later. Maybe an independent consultant or other lone developer can avoid this fate, but a team of normal humans cannot.

Fortunately, Standard.js balances this perfectly - it is as strict as it can be without creating false positives. Whenever Standard bans something, like `void`, it always leaves open some other way to express the same idea, like `undefined` or `=> {}`. In the three years I've been using plain Standard.js, I can count the times I needed `eslint-disable` on one hand, and most of those are in one file.

> It ends up being a choice between stricter linting (which I personally like) which requires a disable-comment some times and more permissive linting that gets out of your way by not requiring that of you. I prefer the former and you seem to not see enough benefit in it.

Exactly! The Standard.js project offers " linting that gets out of your way by not requiring that of you". That's it's whole selling point behind Standard.js, and the reason it is so popular!

As soon as you start requiring disable comments to get basic things done, you start to destroy that wonderful user experience.

You are certainly entitled to your own personal preferences, since this is open source. On the other hand, you have asked @feross for the privilege of being the "official" Typescript solution for Standard.js, and he trusted you with it. Rejecting the basic principle that makes Standard.js useful betrays that trust.

The Standard.js community is counting on `standard-with-typescript` to provide the same Standard.js experience we have had for years, but now with Typescript. Please don't let us down!

**Comment by mightyiam** [comment]
Thank you for explaining. This is a winning point. Going against the spirit of Standard is inappropriate. If that's the case, PR welcome.
