### ISSUE TITLE
@typescript-eslint/prefer-readonly-parameter-types

### ISSUE THREAD

**Issue by mightyiam** [standard/eslint-config-standard-with-typescript#244]
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/prefer-readonly-parameter-types.md

I like the concept but I'm not sure about the `checkParameterProperties` option, because I rarely write any classes.

**Comment by LinusU** [comment]
Woha 😮 it's so cool what lining we can do when we have the full power of the type system!

Although, I have to say, I think that this one might just be too strict. It's really enforcing a particular style of programming, one that I personally use most of the time, but still.

I was actually thinking about the other day, that it would be nice if people added `readonly` to every React prop since in practice the components never modify them. Right now if you try to pass a readonly array as a prop to a React component that doesn't specifically declare it as readonly the compiler won't let you...

**Comment by LinusU** [comment]
Hmm, another example where I think this will be quite annoying, you won't be able to create this function:

```typescript
// Element is not a readonly type
function getElementText (el: Element) {
  return el.textContent
}

getElementText(document.querySelector('.foo'))
```

**Comment by mightyiam** [comment]
Why would that function fail linting, please?

**Comment by LinusU** [comment]
`Element` has properties which are not `readonly`, which means that my function could modify the element. (e.g. by modifying `.textContent` instead of just retrieving it)

**Comment by mightyiam** [comment]
In that case, while this is in interesting rule, it is not suitable for an entire code base. Perhaps only for some specific modules on some architecture paradigms.
