### ISSUE TITLE
Providing specific configuration for react-with-typescript

### ISSUE THREAD

**Issue by felskov** [standard/eslint-config-standard-with-typescript#246]
**What version of this package are you using?**

v14.0.0

**What problem do you want to solve?**

Avoid having to override eslint-config-standard-react with custom rules when using TypeScript.

**What do you think is the correct solution to this problem?**

Would you consider creating a eslint-config-standard-react-with-typescript the same way you already provide eslint-config-standard-with-typescript? For instance react/prop-types makes great sense when not using TypeScript, but in our case the rule forces us to define our props twice (once as a TS interface, once using prop-types). It would be nice if a react-with-typescript config could disable this rule by default.

Also when using React, it makes sense (at least for us) to configure @typescript-eslint/strict-boolean-expressions with ignoreRhs: true, as we frequently use syntax such as {showFeature && <Feature />} . When using eslint-config-standard-with-typescript strict-boolean-expressions are configured to not allow the pattern above, so overwriting with eslint-config-standard-react-with-typescript would be a nice way to avoid having do so manually.

There is probably more things where react+ts specific rules could make sense :)

**Are you willing to submit a pull request to implement this change?**

Yes, but not sure how/where to provide one, as I think a new package would make sense for this configuration.

**Comment by mightyiam** [comment]
Thank you for your suggestion, @felskov.

The intention is clear. A single shareable config to extend from for the case of React plus TypeScript.

Question: not using prop types does seem to make sense in a TypeScript end-project. But what about a React component that is published somehow and could be used in JS or in TS? So that seems like two distinct configs. Is there a TypeScript-based runtime prop validation library that operates in a manner similar to https://github.com/pelotom/runtypes? @pelotom, @patomation.

Regarding the strict-boolean-expressions rule relaxing, that could be discussed outside the context of React, because it seems that it could be widely used in a variety of contexts. So if you care about that, could you please open an issue?

**Comment by LinusU** [comment]
> Regarding the strict-boolean-expressions rule relaxing, that could be discussed outside the context of React, because it seems that it could be widely used in a variety of contexts. So if you care about that, could you please open an issue?

A discussion on this would be nice. When I first applied the config to some larger react code bases I was quite annoyed with this rule. But I have to say that once I've gotten used to it I think that I quite like it ☺️

**Comment by patomation** [comment]
> Question: not using prop types does seem to make sense in a TypeScript end-project. But what about a React component that is published somehow and could be used in JS or in TS? So that seems like two distinct configs. Is there a TypeScript-based runtime prop validation library that operates in a manner similar to https://github.com/pelotom/runtypes?

I can chime in on regarding PropTypes. While I'm not satisfied with this solution there is a plugin called: (babel-plugin-typescript-to-proptypes)[https://github.com/milesj/babel-plugin-typescript-to-proptypes]

The thing I don't care for is that I have to go through babel to trans-pile TypeScript. So right now I use a typescript plugin within babel. The result is generated prop types added at build time.

With Eslint I'm still having to manually disable the ```react/prop-types``` rule.   

An example of this can be round here: (react-npm-package-starter)[https://github.com/patomation/react-npm-package-starter]

I hope this helps, at least, shed some light into one way of doing things.

**Comment by LinusU** [comment]
Speaking of prop-types btw, are those still recommended by React? I know that react-native is removing them 🤔

**Comment by patomation** [comment]
I would be interested in knowing if they plan to keep it. 2 years ago @gaearon mentioned that they don't have any plans to remove them. But he also said they don't promote them because flow and typescript "do a better job." I would imagine with the way updating software goes prop-types might get remove simply because the code base changed enough for it to not be worth implementing or maintaining? This is just conjecture, but I would be happy with not including them in the future. What do you think?

**Comment by LinusU** [comment]
I would personally be okay with completely removing the `react/prop-types` rule ☺️

**Comment by mightyiam** [comment]
Hello from two years later. Whatever the perceived problem is and whatever the solution may be, it's unlikely to be a change in this project, as this project shouldn't be influenced by React or any other unrelated library.

Please feel free to continue discussion regarding where this discussion belongs and then when you figure that out, please take the discussion there.
